### ISSUE TITLE
Handle task status in unsupported scenario

### ISSUE THREAD

**Issue by gmarupilla** [biosimulators/Biosimulators_VCell#59]
@jonrkarr,

I have some doubts related to status.yml and how it's being updated through VCELL CLI.
VCell doesn't support any processing or generation of plots, and it can only generate reports.

If we provide an omex for simulation where there are tasks, plots, and no reports, the simulation will complete. Still, no plots will be generated (since vcell doesn't support them), and no CSV will be generated (because no report spec was provided in SEDML).

In this case, what should be the status of individual tasks and complete simulation?

[status.yml.zip](https://github.com/biosimulators/Biosimulators_VCell/files/6018205/status.yml.zip)

For example, line 78 to line 89 in attached status.yml, 

(A) what should be their status in this scenario? Should it be skipped or succeeded?

(B) If one of the tasks fails, what should be the status in that case?

(C) What should be the SEDML status in line 76 if
	(1) All task succeed
	(2) One of the tasks fails

**Comment by jonrkarr** [comment]
For VCell, plots should have the status `SKIPPED`. The reason for the skip should be something like "SED plots are not supported."

Failures should "bubble up". If a task in a SED document fails, the task should have status `FAILED`, its parent SED document should have status `FAILED`, and the parent COMBINE archive should have status `FAILED`.

Skips are not intended to bubble up. If a plot is skipped, the plot should have status "SKIPPED", but its SED document and COMBINE archive could have status `SUCCEEDED` (unless there's a failure). I think this will be clear to users because the UI is just going to show the status of the individual tasks and outputs. Users will be able to use that information to decide how to interpret skips and whether they need to change their SED file(s).

If a COMBINE archive had 1 SED document with 1 task which succeeded and 1 plot which was skipped the log would look something like this
```yaml
status: SUCCEEDED
sedDocuments:
  - location: doc1.sedml
  - status: SUCCEEDED
  - tasks:
     - id: task1
       status: SUCCEEDED
    - outputs:
     - id: plot1
       status: SKIPPED 
       skipReason:
         - category: PlotsNotSupported
         - message: SED plots are not supported
```
    

If the task failed, the log would look like this
```yaml
status: FAILED
sedDocuments:
  - location: doc1.sedml
  - status: FAILED
  - tasks:
     - id: task1
       status: FAILED
    - outputs:
     - id: plot1
       status: SKIPPED 
       skipReason:
         - category: PlotsNotSupported
         - message: SED plots are not supported
```

If the task failed and there was a report (which was skipped because the data for the report isn't available due to the task failure), the log could look like this
```yaml
status: FAILED
sedDocuments:
  - location: doc1.sedml
  - status: FAILED
  - tasks:
     - id: task1
       status: FAILED
    - outputs:
     - id: plot1
       status: SKIPPED 
       skipReason:
         - category: PlotsNotSupported
         - message: SED plots are not supported
     - id: report1
       status: SKIPPED 
       skipReason:
         - category: DataNotAvailable
         - message: Report could not be assembled because the source task(s) failed
```
